version: "3.7"

services:
  mysql:
    image: bitnami/mysql:8.0
    ports:
      - "3306:3306"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: telegame
      MYSQL_ROOT_PASSWORD: telegame
    volumes:
      - "mysql-data:/bitnami/mysql"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/bitnami/redis"
volumes:
  mysql-data:
  redis-data:
